### ISSUE TITLE
I'm getting errors. What version of Node and other environments are you running?

### ISSUE THREAD

**Issue by Realsupersaiyan** [TheDemise/discord.js-musicbot-addon#6]
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at PassThrough.Writable.write (_stream_writable.js:288:21)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at emitThree (events.js:140:20)
    at DestroyableTransform.emit (events.js:216:7)
    at emitThree (events.js:135:13)
    at FfmpegCommand.emit (events.js:216:7)
    at emitEnd (/home/luis/Haruhi Bot/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/luis/Haruhi Bot/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at /home/luis/Haruhi Bot/node_modules/async/dist/async.js:421:16

**Comment by TheDemise** [comment]
Someone else was getting this error after the 1.4 update. If you're using 1.4+, you need to have [ffmpeg](https://ffmpeg.org/) installed and in your PATH environment variable, rather than the prior updates that use the ffmpeg-binaries module. It was my mistake to not realize that in that update. But it has been noted in the readme.

Node 8+ (recommended, _might_ work with older versions) and ffmpeg are all that's required for 1.4+ updates since it changed the way music is played/searched. Well that and a YouTube API3 key.

If for some reason you're using a lower version, I can't really say much besides update to the latest build.

**Comment by Realsupersaiyan** [comment]
I'm using Ubuntu to run it. That's where the problem starts.

**Comment by Realsupersaiyan** [comment]
Ytdl-core works for me, but Youtube-audio-stream doesn't.

**Comment by TheDemise** [comment]
That shouldn't be a problem.
_Did_ you try installing ffmpeg correctly before? As well as making sure it's installed, and re-installing all modules?

Also, just to note, `ytdl-core` was causing issues. Such as ending audio midway, errors related to audio, along with a few other annoyances, so I tried a couple other things and `youtube-audio-stream` hasn't caused any issues that haven't been able to be fixed.

**Comment by Realsupersaiyan** [comment]
Is it alright if I installed ffmpeg through npm?

**Comment by TheDemise** [comment]
No, you need ffmpeg itself installed, probably one of these since you're on Ubuntu https://ffmpeg.org/download.html#build-linux.
If you don't know how to set it up, I can't help much but tell you to search about it online.

**Comment by Realsupersaiyan** [comment]
I'm an idiot. That worked. Thanks very much!

**Comment by TheDemise** [comment]
No problem.
